### PR TITLE
Fix broken link and update file name in README.md

### PR DESCRIPTION
**Pull request by Ioana37**
The purpose of this PR is to make the following changes to the Readme file for te QuickStart using vectors:
- fix a broken link
- replace a file name with the correct one

### CODE REVIEW

**Comment by Ioana37** [comment]
@HeidiSteen please take a look at this PR

**Review by HeidiSteen — APPROVED** [review]
Thank you!

**Comment by Ioana37** [comment]
@HeidiSteen thank you for the review! Could we merge this PR?

**Review by HeidiSteen — APPROVED** [review]
thanks!

**Pull request merged**
